language: python
env:
  global:
    - SKIP_IMAGE_CHECK=1
  matrix:
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=sphinx10
    - TOXENV=sphinx11
    - TOXENV=sphinx12
    - TOXENV=coverage
install: pip install docutils tox
script: tox
